"""Blue Team Adversarial Simulator.

Tracks noise generated by the "Red Team" tools and triggers retaliatory
actions like port blocking or account disabling when thresholds are crossed.
"""
from openworlds.world_engine.models import Manifest

class BlueTeamAgent:
    """Simulates an EDR / SOC analyst reacting to red team noise."""

    def __init__(self, manifest: Manifest):
        self.manifest = manifest
        # Global network alert level (0 to 100+)
        self.network_alert_level: float = 0.0
        
        # Track locked out resources
        self.blocked_ips: set[str] = set()
        self.disabled_accounts: set[str] = set()
        self.closed_ports_by_ip: dict[str, set[int]] = {}

    def report_noise(self, source_ip: str | None, command: str, target: str, noise_score: float) -> str | None:
        """Report a noisy action. Returns a retaliation message if blocked."""
        # If already blocked, return immediately
        if source_ip and source_ip in self.blocked_ips:
            return f"Error: Connection to {target} timed out (IP {source_ip} is blocked by firewall)."
            
        self.network_alert_level += noise_score
        
        # Trigger dynamic defenses
        return self._evaluate_thresholds(source_ip, command, target)

    def _evaluate_thresholds(self, source_ip: str | None, command: str, target: str) -> str | None:
        """Evaluate if retaliation thresholds are met and execute defense."""
        retaliation = []

        # Tier 1: Moderate suspicion (30-60 alert level)
        if self.network_alert_level > 30 and "nmap" in command and "-p-" in command:
            if target not in self.closed_ports_by_ip:
                self.closed_ports_by_ip[target] = set()
            self.closed_ports_by_ip[target].update([445, 135, 3389])
            retaliation.append(f"EDR Alert Triggered: High-velocity port scan detected on {target}. Sensitive ports dynamically filtered.")

        # Tier 2: High suspicion (60-90 alert level)
        if self.network_alert_level > 60 and ("crackmapexec" in command or "kerberoast" in command):
            # Find the user account being used and lock it
            for word in command.split():
                if "\\" in word or "@" in word or "-u " in command:
                    # In a real impl, we'd extract the user precisely, but we'll flag it broadly for now
                    retaliation.append("SOC Action: Suspicious Kerberos/SMB anomalies. Service accounts rotating or disabled temporarily.")
                    break

        # Tier 3: Critical incident (90+ alert level)
        if self.network_alert_level > 95:
            if source_ip:
                self.blocked_ips.add(source_ip)
                retaliation.append(f"CRITICAL: SOC isolated IP {source_ip} from the network. Connection forcibly disconnected.")

        return "\n".join(retaliation) if retaliation else None

    def is_port_blocked(self, target_ip: str, port: int) -> bool:
        """Check if a specific port on a target IP has been dynamically blocked."""
        return port in self.closed_ports_by_ip.get(target_ip, set())
